[project]
name = "just_read"
version = "0.1.0"
description = "Project-based reading tracking app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
