[project]
name = "just-read"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django===5.2",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.16.1",
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
]
