# Generated by Django 5.2 on 2025-10-03 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_project.reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='active_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_readers', to='core_project.readingproject'),
        ),
        migrations.CreateModel(
            name='TextualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=200)),
                ('progress_percent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Did Not Finish', 'Did Not Finish'), ('On Hold', 'On Hold'), ('Planned', 'Planned')], default='Not Started', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('dnf_date', models.DateField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_project.readingproject')),
            ],
        ),
    ]
