# Generated by Django 5.2 on 2025-10-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingproject',
            name='active_project',
            field=models.BooleanField(default=False),
        ),
    ]
